### ISSUE TITLE
Can we fix the TS decorators import?

### ISSUE THREAD

**Issue by jaydanurwin** [litelement-dev/lit-snippets#1]
First of all thank you so much for this awesome extension, I use it all the time!

I only have ran into one issue so far.

It seems that the TS snippet defaults to `import { customElement, property } from 'lit/decorators'` whereas it should be `import { customElement, property } from 'lit/decorators.js'`

I have to fix it every time to `.js`. If you would like me to submit a PR to save time I'm happy to just figured I'd open the issue first.

Thanks again!

**Comment by herberthobregon** [comment]
Sure! I working on that now

**Comment by herberthobregon** [comment]
Done. Wait 30 minutes to watch the launch live.

**Comment by jaydanurwin** [comment]
Wow you're quick! Thanks for jumping on that so fast. I'll be sure to keep recommending it to people! 👍🏼
